export const ADD_NEW_PIZZA_TO_CART: 'ADD_NEW_PIZZA_TO_CART' = 'ADD_NEW_PIZZA_TO_CART';

export const CLEAR_CART: 'CLEAR_CART' = 'CLEAR_CART';

export const REDUCE_COUNT: 'REDUCE_COUNT' = 'REDUCE_COUNT';
export const INCREASE_COUNT: 'INCREASE_COUNT' = 'INCREASE_COUNT';
export const DELETE_ORDER: 'DELETE_ORDER'= 'DELETE_ORDER';

export const LOAD_CART_STATE: 'LOAD_CART_STATE' = 'LOAD_CART_STATE';