import { IpizzaDescription } from "../interfaces/interfaces"


export const pizzaDescription: IpizzaDescription[] = [
  {
    id: 0,
    title: 'Сheeseburger-Pizza',
    type: 'meat',
    image: 'https://dodopizza.azureedge.net/static/Img/Products/Pizza/ru-RU/b750f576-4a83-48e6-a283-5a8efb68c35d.jpg',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 15,
  },
  {
    id: 1,
    title: 'Cheesy',
    type: 'vegetarian',
    image: 'https://dodopizza.azureedge.net/static/Img/Products/Pizza/ru-RU/2ffc31bb-132c-4c99-b894-53f7107a1441.jpg',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 15,
  },
  {
    id: 2,
    title: 'Pepperoni Fresh with pepper',
    type: 'spicy',
    image: 'https://dodopizza.azureedge.net/static/Img/Products/f035c7f46c0844069722f2bb3ee9f113_584x584.jpeg',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 40,
  },
  {
    id: 3,
    title: 'BBQ chicken',
    type: 'meat',
    image: 'https://dodopizza.azureedge.net/static/Img/Products/Pizza/ru-RU/6652fec1-04df-49d8-8744-232f1032c44b.jpg',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 20,
  },
  {
    id: 4,
    title: 'Sweet and sour chicken',
    type: 'meat',
    image: 'https://dodopizza.azureedge.net/static/Img/Products/Pizza/ru-RU/af553bf5-3887-4501-b88e-8f0f55229429.jpg',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 27,
  },
  {
    id: 5,
    title: 'Crazy pepperoni',
    type: 'spicy',
    image: 'https://dodopizza.azureedge.net/static/Img/Products/Pizza/ru-RU/1e1a6e80-b3ba-4a44-b6b9-beae5b1fbf27.jpg',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 30,
  },
  {
    id: 6,
    title: 'Pepperoni',
    type: 'meat',
    image: 'https://dodopizza.azureedge.net/static/Img/Products/Pizza/ru-RU/d2e337e9-e07a-4199-9cc1-501cc44cb8f8.jpg',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 20,
  },
  {
    id: 7,
    title: 'Margarita',
    type: 'meat',
    image: 'https://dodopizza.azureedge.net/static/Img/Products/Pizza/ru-RU/d48003cd-902c-420d-9f28-92d9dc5f73b4.jpg',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 32,

  },
  {
    id: 8,
    title: 'Four seasons',
    type: 'meat',
    image: 'https://dodopizza.azureedge.net/static/Img/Products/Pizza/ru-RU/ec29465e-606b-4a04-a03e-da3940d37e0e.jpg',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 25,

  },
  {
    id: 9,
    title: 'Vegetables and mushrooms',
    type: 'vegetarian',
    image: 'https://dodopizza.azureedge.net/static/Img/Products/Pizza/ru-RU/30367198-f3bd-44ed-9314-6f717960da07.jpg',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 27,
  },
  {
    id: 10,
    title: 'Riviera',
    type: 'meat',
    image: 'https://images.dominos.by/media/dominos/osg/api/2021/03/23/rivyera_small_mNcDSaS.png',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 30,

  },
  {
    id: 11,
    title: '5 Cheese',
    type: 'vegetarian',
    image: 'https://images.dominos.by/media/dominos/osg/api/2018/09/12/5_syrov.png',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 25.49,
  },
  {
    id: 12,
    title: 'Bavarian',
    type: 'spicy',
    image: 'https://images.dominos.by/media/dominos/osg/api/2019/07/03/bavarchkaya_small.png',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 24.39,
  },
  {
    id: 13,
    title: 'Vegetable',
    type: 'vegetarian',
    image: 'https://images.dominos.by/media/dominos/osg/api/2018/09/12/ovoshchnaya.png',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 24.39,
  },
  {
    id: 14,
    title: 'Mexican',
    type: 'spicy',
    image: 'https://images.dominos.by/media/dominos/osg/api/2021/06/10/meksikanskaya_small.png',
    availableBase: ['thin', 'traditional'],
    availableSizes: ['small', 'medium', 'large'],
    startPrice: 25.99,
  },
];